version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: taskdb-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb


volumes:
  mongodb_data: